[project]
name = "multi-agent-sql-murder-mystery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai[logfire]>=0.0.48",
    "pydantic-graph>=0.0.48",
]
